### ISSUE TITLE
Error: Unexpected value 'WizardModule' imported by the module 'DemoMenuDemoModule'. 

### ISSUE THREAD

**Issue by jperezdelafuente** [sudheerj/generator-jhipster-primeng#17]
When I run "yarn start" I get this error in the console of browser:

Uncaught Error: Unexpected value 'WizardModule' imported by the module 'DemoMenuDemoModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.es5.js?524d:1690)
    at eval (compiler.es5.js?524d:15386)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js?524d:15369)
    at CompileMetadataResolver.getNgModuleSummary (compiler.es5.js?524d:15311)
    at eval (compiler.es5.js?524d:15384)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js?524d:15369)
    at CompileMetadataResolver.getNgModuleSummary (compiler.es5.js?524d:15311)
    at eval (compiler.es5.js?524d:15384)

System info:
- Gradle 4.2.1
- Node 6.11.3
- npm 5.4.2
- yarn 1.2.1
- yeoman 2.0
- jhipster 4.10.0
- generator-jhipster-primeng 1.0.20
- Windows 10

Consig generator-jhipster-primeng:
? Do you want to install PrimeNG? Yes
? Which theme would you like to use? Kasper
? What is the preferred component selection criteria Component Groups
? Which component groups you would like to use? inputs

**Comment by sudheerj** [comment]
Can you do npm install on your project before doing yarn start or npm start. If still it creates an issue then please inform us.

**Comment by jperezdelafuente** [comment]
I delete "node_modules", I invoke "npm install" and after "npm start" and "gradle" (in other console) and the problem is resolve.

But, if I invoke "gradle -Pprod" (mode with optimizations to production), I get this error in the console:

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in D:/IoT/work_jhipster/demo/node_modules/primeng-extensions-wizard/node_modules/@angular/core/core.d.ts, resolving symbol WizardModule in D:/IoT/work_jhipster/demo/node_modules/primeng-extensions-wizard/components/wizard.module.d.ts, resolving symbol WizardModule in D:/IoT/work_jhipster/demo/node_modules/primeng-extensions-wizard/components/wizard.module.d.ts
    at positionalError (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:25108:35)
    at simplifyInContext (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24951:27)
    at StaticReflector.simplify (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24965:13)
    at StaticReflector.annotations (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24395:41)
    at NgModuleResolver.resolve (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:14737:70)
    at CompileMetadataResolver.getNgModuleMetadata (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:15390:60)
    at addNgModule (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24245:58)
    at D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24256:14
    at Array.forEach (native)
    at _createNgModules (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24255:26)
    at analyzeNgModules (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24130:14)
    at analyzeAndValidateNgModules (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:24140:35)
    at AotCompiler.analyzeModulesAsync (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler\bundles\compiler.umd.js:23776:46)
    at CodeGenerator.codegen (D:\IoT\work_jhipster\demo\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at D:\IoT\work_jhipster\demo\node_modules\ngc-webpack\src\main.js:12:103
    at Object.main (D:\IoT\work_jhipster\demo\node_modules\@angular\tsc-wrapped\src\main.js:106:16)
    at Object.runInternal (D:\IoT\work_jhipster\demo\node_modules\ngc-webpack\src\main.js:16:27)
    at D:\IoT\work_jhipster\demo\node_modules\ngc-webpack\src\plugin.js:54:48
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

And, if I invoke "npm start" again, I get the previous error in the console of the browser: Uncaught Error: Unexpected value 'WizardModule' imported by the module 'DemoMenuDemoModule'. Please add a @NgModule annotation.
