### ISSUE TITLE
Compatibility with production mode of Jhipster

### ISSUE THREAD

**Issue by jperezdelafuente** [sudheerj/generator-jhipster-primeng#19]
Is generator-jhipster-primeng module compatible with production mode of Jhipster?

When I invoke "gradle -Pprod" (mode with optimizations to production), I get this error in the console:

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in D:/IoT/work_jhipster/demo/node_modules/primeng-extensions-wizard/node_modules//core.d.ts, resolving symbol WizardModule in D:/IoT/work_jhipster/demo/node_modules/primeng-extensions-wizard/components/wizard.module.d.ts, resolving symbol WizardModule in D:/IoT/work_jhipster/demo/node_modules/primeng-extensions-wizard/components/wizard.module.d.ts
at positionalError (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:25108:35)
at simplifyInContext (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24951:27)
at StaticReflector.simplify (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24965:13)
at StaticReflector.annotations (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24395:41)
at NgModuleResolver.resolve (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:14737:70)
at CompileMetadataResolver.getNgModuleMetadata (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:15390:60)
at addNgModule (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24245:58)
at D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24256:14
at Array.forEach (native)
at _createNgModules (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24255:26)
at analyzeNgModules (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24130:14)
at analyzeAndValidateNgModules (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:24140:35)
at AotCompiler.analyzeModulesAsync (D:\IoT\work_jhipster\demo\node_modules@angular\compiler\bundles\compiler.umd.js:23776:46)
at CodeGenerator.codegen (D:\IoT\work_jhipster\demo\node_modules@angular\compiler-cli\src\codegen.js:32:14)
at D:\IoT\work_jhipster\demo\node_modules\ngc-webpack\src\main.js:12:103
at Object.main (D:\IoT\work_jhipster\demo\node_modules@angular\tsc-wrapped\src\main.js:106:16)
at Object.runInternal (D:\IoT\work_jhipster\demo\node_modules\ngc-webpack\src\main.js:16:27)
at D:\IoT\work_jhipster\demo\node_modules\ngc-webpack\src\plugin.js:54:48
at process._tickCallback (internal/process/next_tick.js:109:7)
at Module.runMain (module.js:606:11)
at run (bootstrap_node.js:389:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:502:3
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sudheerj** [comment]
The error is originated from Primeng-extensions-wizard library which I used for component feature navigations. I will check with author of this library and get back to you.

**Comment by jperezdelafuente** [comment]
Great! 
I already have it working in production mode without the wizard component.
Although it would be interesting also to have the wizard component in production mode.

**Comment by sudheerj** [comment]
Still the investigation is happening with wizard module. I will close the issue and create a new issue specific to Wizard issue in PROD.
