### ISSUE TITLE
Generator TypeError: this.copyExternalAssetsInWebpack is not a function

### ISSUE THREAD

**Issue by djorgji** [sudheerj/generator-jhipster-primeng#4]
I have tried this in a myriad of ways and with the latest jhipster from yarn (4.9) and latest latest jh-primeng, still getting the same error. I have even tried including all components.

```
Welcome to the JHipster primeng generator! v0.0.74

? Do you want to install PrimeNG? Yes
? Which theme would you like to use? Omega
? Which components you would like to include? inputs
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.copyExternalAssetsInWebpack is not a function
    at constructor.writing (/home/dev/.config/yarn/global/node_modules/generator-jhipster-primeng/generators/app/index.js:646:14)
    at Object.<anonymous> (/home/dev/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/dev/.config/yarn/global/node_modules/run-async/index.js:25:25
    at /home/dev/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/dev/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

**Comment by sudheerj** [comment]
The JHipster-PrimeNG module is not yet released due to changes in Core Jhipster. The initial release is available after merge request ported. https://github.com/jhipster/generator-jhipster/pull/6494

**Comment by sudheerj** [comment]
Please try with latest version now.  Some of the components don't work properly until you copy scripts shown in the instructions or till the next release of JHipster. You can reopen the issue for any concerns.
