### ISSUE TITLE
Error in installation - events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by kalyandas75** [sudheerj/generator-jhipster-primeng#6]
Welcome to the JHipster primeng generator! v0.0.74

? Do you want to install PrimeNG? Yes
? Which theme would you like to use? Omega
? Which components you would like to include? inputs, buttons, data, panel, overlay, file, menu, charts, messages, mult
imedia, dragdrop, misc
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.copyExternalAssetsInWebpack is not a function
    at constructor.writing (C:\Users\kalyan\AppData\Roaming\npm\node_modules\generator-jhipster-primeng\generators\app\index.js:646:14)
    at Object.<anonymous> (C:\Users\kalyan\AppData\Roaming\npm\node_modules\generator-jhipster-primeng\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\kalyan\AppData\Roaming\npm\node_modules\generator-jhipster-primeng\node_modules\generator-jhipster\node_modules\run-async\index.js:25:25
    at C:\Users\kalyan\AppData\Roaming\npm\node_modules\generator-jhipster-primeng\node_modules\generator-jhipster\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\kalyan\AppData\Roaming\npm\node_modules\generator-jhipster-primeng\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by sudheerj** [comment]
Thank you. Can you please try with latest version 0.0.85. Please comment and reopen if you still face an issue.
